TechSwap/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
import debug_toolbar

urlpatterns = [
    path("ts-admin/", admin.site.urls),
    path("", include("swapshop.urls")),
    path("accounts/", include("allauth.urls")),
]

if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include(debug_toolbar.urls)),
    ]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

swapshop/urls.py
from django.urls import path

# from django.views.generic import TemplateView

from .views import (
    HomeView,
    AboutView,
    AllItemsView,
    ItemDetailView,
    GuestItemDetailView,
    ItemCreateView,
    AddToWishListView,
    MyWishListView,
    MyItemListView,
    ManageWishListView,
    EmptyWishListView,
    UserProfileView,
    UserItemDetailView,
    SearchView,
    RemWishListItemView,
    RemMyItemView,
    ArcMyItemView,
    NotYourItemView,
    MySwapListView,
    RequestSwapView,
    EmptySwapListView,
    RemSwapListItemView,
    SwapDetailView,
    AddToSwapListView,
    WLItemDetailView,
    AlreadyRequestedView,
    SuccessView,
    SwapSuccessView,
)

app_name = "swapshop"
urlpatterns = [
    # Client side pages
    path("", HomeView.as_view(), name="home"),
    path("about/", AboutView, name="about"),
    path("success/", SuccessView, name="success"),
    path("swapsuccess/", SwapSuccessView, name="swapsuccess"),
    path("all-items/", AllItemsView.as_view(), name="allitems"),
    path("item/<slug:slug>/", ItemDetailView.as_view(), name="itemdetail"),
    path("wlitem/<slug:slug>/", WLItemDetailView.as_view(), name="wlitemdetail"),
    path("swap/<slug:slug>/", SwapDetailView.as_view(), name="swapdetail"),
    path(
        "guestitem/<slug:slug>/", GuestItemDetailView.as_view(), name="guestitemdetail"
    ),
    path("additem/", ItemCreateView.as_view(), name="itemcreate"),
    path("add-to-wlist-<int:itm_id>/", AddToWishListView.as_view(), name="addtowlist"),
    path("add-to-slist-<int:itm_id>/", AddToSwapListView.as_view(), name="addtoslist"),
    path("my-item-list/", MyItemListView.as_view(), name="myitemlist"),
    path("my-wish-list/", MyWishListView.as_view(), name="mywishlist"),
    path("my-swap-list/", MySwapListView.as_view(), name="myswaplist"),
    path("manage-list/<int:cp_id>/", ManageWishListView.as_view(), name="managelist"),
    path("emptywishlist/", EmptyWishListView.as_view(), name="emptywishlist"),
    path("rem-wlitem/<slug:slug>/", RemWishListItemView.as_view(), name="remwlitem"),
    path("rem-myitem/<slug:slug>/", RemMyItemView.as_view(), name="remmyitem"),
    path("arc-myitem/<slug:slug>/", ArcMyItemView.as_view(), name="arcmyitem"),
    path("emptyswaplist/", EmptySwapListView.as_view(), name="emptyswaplist"),
    path("rem-slitem/<slug:slug>/", RemSwapListItemView.as_view(), name="remslitem"),
    path("reqswap-<int:itm_id>/", RequestSwapView, name="reqswap"),
    path("notyouritem/", NotYourItemView.as_view(), name="notyouritem"),
    path("alreadyrequested/", AlreadyRequestedView.as_view(), name="alreadyrequested"),
    path("accounts/profile/", UserProfileView.as_view(), name="userprofile"),
    path(
        "accounts/profile/item-<int:pk>/",
        UserItemDetailView.as_view(),
        name="useritemdetail",
    ),
    path("search/", SearchView.as_view(), name="search"),
]

templates/navbar/nav_authenticated.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'swapshop:home' %}"><img class="rounded float-left" src="{% static '/assets/images/logo.png' %}" width="100" alt="TechSwap"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                <li {% if request.path == "/" %} class="nav-item active" {% else %} class="nav-item" {% endif %}>
                    <a class="nav-link" href="{% url 'swapshop:home' %}">Home <span class="sr-only">(current)</span></a>
                </li>
                <li {% if request.path == "/about/" %} class="nav-item active"{% else %} class="nav-item" {% endif %}> <a class="nav-link" a href="{% url 'swapshop:about' %}">About</a></li>
                {% comment %} <li {% if request.path == "/social/" %} class="nav-item active"{% else %} class="nav-item" {% endif %}><a class="nav-link" href="{% url 'swapshop:social' %}">Community</a></li> {% endcomment %}
                {% comment %} <li {% if request.path == "/contact-us/" %} class="nav-item active"{% else %} class="nav-item" {% endif %}><a class="nav-link" href="{% url 'swapshop:contact' %}">Contact</a></li> {% endcomment %}
                <li {% if request.path == "/accounts/profile/" %} class="nav-item dropdown active" {% else %} class="nav-item dropdown" {% endif %}>
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    My Account
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{% url 'account_email' %}">Change E-mail</a>
                        <a class="dropdown-item" href="{% url 'swapshop:userprofile' %}">My Profile</a>
                        <a class="dropdown-item" href="{% url 'account_logout' %}">Logout</a>
                    </div>
                </li>
                <li {% if request.path == "/my-item-list/" or request.path == "/my-wish-list/" or request.path == "/my-swap-list/" or request.path == "/additem/" %} class="nav-item dropdown active" {% else %} class="nav-item dropdown" {% endif %}>
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Swaps</a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{% url 'swapshop:myitemlist' %}">My Items</a>
                            <a class="dropdown-item" href="{% url 'swapshop:mywishlist' %}">My Wish List</a>
                            <a class="dropdown-item" href="{% url 'swapshop:myswaplist' %}">My Swap List</a>
                            <a class="dropdown-item" href="{% url 'swapshop:itemcreate' %}">New Item</a>
                        </div>
                </li> 
            </ul>
        </div>
        <form class="form-inline mx-auto my-2 my-lg-0" action="{% url 'swapshop:search' %}" method="GET">
            <input name="keyword" class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" required>
            <button class="btn btn-danger my-2 my-sm-0" type="submit">Search</button>
        </form>
        
</nav>

templates/navbar/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'swapshop:home' %}"><img class="rounded float-left" src="{% static '/assets/images/logo.png' %}" width="100" alt="TechSwap"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
            <li {% if request.path == "/" %} class="nav-item active" {% else %} class="nav-item" {% endif %}>
                <a class="nav-link" href="{% url 'swapshop:home' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li {% if request.path == "/about/" %} class="nav-item active" {% else %} class="nav-item" {% endif %}><a class="nav-link" a href="{% url 'swapshop:about' %}">About</a></li>
            {% comment %} <li {% if request.path == "/social/" %} class="nav-item active" {% else %} class="nav-item" {% endif %}><a class="nav-link" href="{% url 'swapshop:social' %}">Community</a></li> {% endcomment %}
            {% comment %} <li {% if request.path == "/contact-us/" %} class="nav-item active" {% else %} class="nav-item" {% endif %}><a class="nav-link" href="{% url 'swapshop:contact' %}">Contact</a></li> {% endcomment %}
            <li {% if request.path == "/accounts/signup/" or request.path == "/accounts/login/" %} class="nav-item dropdown active" {% else %} class="nav-item dropdown" {% endif %}>
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                My Account
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'account_signup' %}">Register</a>
                    <a class="dropdown-item" href="{% url 'account_login' %}">Login</a>
                </div>
            </li>
        </ul>
        <form class="form-inline my-2 my-lg-0" action="{% url 'swapshop:search' %}" method="GET">
        <input name="keyword" class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" required>
        <button class="btn btn-danger my-2 my-sm-0" type="submit">Search</button>
        </form>
    </div>
</nav>