TechSwap/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
import debug_toolbar

urlpatterns = [
    path("ts-admin/", admin.site.urls),
    path("", include("swapshop.urls")),
    path("accounts/", include("allauth.urls")),
]

if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include(debug_toolbar.urls)),
    ]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

swapshop/urls.py
from django.urls import path

# from django.views.generic import TemplateView

from .views import (
    HomeView,
    AboutView,
    AllItemsView,
    ItemDetailView,
    GuestItemDetailView,
    ItemCreateView,
    AddToWishListView,
    MyWishListView,
    MyItemListView,
    ManageWishListView,
    EmptyWishListView,
    UserProfileView,
    UserItemDetailView,
    SearchView,
    RemWishListItemView,
    RemMyItemView,
    ArcMyItemView,
    NotYourItemView,
    MySwapListView,
    RequestSwapView,
    EmptySwapListView,
    RemSwapListItemView,
    SwapDetailView,
    AddToSwapListView,
    WLItemDetailView,
    AlreadyRequestedView,
    SuccessView,
    SwapSuccessView,
)

app_name = "swapshop"
urlpatterns = [
    # Client side pages
    path("", HomeView.as_view(), name="home"),
    path("about/", AboutView, name="about"),
    path("success/", SuccessView, name="success"),
    path("swapsuccess/", SwapSuccessView, name="swapsuccess"),
    path("all-items/", AllItemsView.as_view(), name="allitems"),
    path("item/<slug:slug>/", ItemDetailView.as_view(), name="itemdetail"),
    path("wlitem/<slug:slug>/", WLItemDetailView.as_view(), name="wlitemdetail"),
    path("swap/<slug:slug>/", SwapDetailView.as_view(), name="swapdetail"),
    path(
        "guestitem/<slug:slug>/", GuestItemDetailView.as_view(), name="guestitemdetail"
    ),
    path("additem/", ItemCreateView.as_view(), name="itemcreate"),
    path("add-to-wlist-<int:itm_id>/", AddToWishListView.as_view(), name="addtowlist"),
    path("add-to-slist-<int:itm_id>/", AddToSwapListView.as_view(), name="addtoslist"),
    path("my-item-list/", MyItemListView.as_view(), name="myitemlist"),
    path("my-wish-list/", MyWishListView.as_view(), name="mywishlist"),
    path("my-swap-list/", MySwapListView.as_view(), name="myswaplist"),
    path("manage-list/<int:cp_id>/", ManageWishListView.as_view(), name="managelist"),
    path("emptywishlist/", EmptyWishListView.as_view(), name="emptywishlist"),
    path("rem-wlitem/<slug:slug>/", RemWishListItemView.as_view(), name="remwlitem"),
    path("rem-myitem/<slug:slug>/", RemMyItemView.as_view(), name="remmyitem"),
    path("arc-myitem/<slug:slug>/", ArcMyItemView.as_view(), name="arcmyitem"),
    path("emptyswaplist/", EmptySwapListView.as_view(), name="emptyswaplist"),
    path("rem-slitem/<slug:slug>/", RemSwapListItemView.as_view(), name="remslitem"),
    path("reqswap-<int:itm_id>/", RequestSwapView, name="reqswap"),
    path("notyouritem/", NotYourItemView.as_view(), name="notyouritem"),
    path("alreadyrequested/", AlreadyRequestedView.as_view(), name="alreadyrequested"),
    path("accounts/profile/", UserProfileView.as_view(), name="userprofile"),
    path(
        "accounts/profile/item-<int:pk>/",
        UserItemDetailView.as_view(),
        name="useritemdetail",
    ),
    path("search/", SearchView.as_view(), name="search"),
]

templates/abouthead.html
<header class="bg-dark py-2">
    <div class="container px-4 px-lg-5 my-1">
        <div class="text-center text-white">
            <h1 class="display-4 fw-bolder">About Us</h1>
            <p class="lead fw-normal text-white-50 mb-0">Welcome to TechSwap....</p>
        </div>
    </div>
</header>

templates/alreadyrequestedhead.html
<header class="bg-danger py-2">
    <div class="container px-4 px-lg-5 my-1">
        <div class="text-center text-white">
            <h1 class="display-4 fw-bolder">Swap already Initiated</h1>
            <p class="lead fw-normal text-white-50 mb-0">Welcome to TechSwap....</p>
        </div>
    </div>
</header>

templates/base.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>TechSwap</title>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="From me to you to me" />
        <meta name="author" content="l1dge" />
        {% load static %}
        
        
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static "/assets/favicon.ico" %}" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link rel="stylesheet" href="{% static "/css/styles.css"  %}" />
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"/>
        <!-- FontAwesome Icons -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" type="text/css"/>
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://polyfill.io/v3/polyfill.min.js?features=default"></script>
        <script src="{% static "/js/scripts.js" %}"></script>
        <link rel="stylesheet" href="{% static "/css/starter.css"  %}" type="text/css"/>
        <link rel="stylesheet" href="{% static "/css/sticky-footer.css"  %}" type="text/css"/>
        {{ form.media  }}
    </head>
    <body>
    
        {% include 'nav.html' %}
        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="#">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
        {% if messages %}
        <div>
        <strong>Messages:</strong>
        <ul>
            {% for message in messages %}
            <li>{{message}}</li>
            {% endfor %}
        </ul>
        </div>
        {% endif %}
        
        {% block content %}
        
                       
        
        {% endblock %}
        {% include 'footer.html' %}  
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script> 
    
     
    </body>
</html>

templates/contactus.html
{% extends 'base.html' %}

{% block content %}

{% include 'contacthead.html' %}

    <h1>Contact Support</h1>
    <p>This is a template</p>


{% endblock %}

templates/footer.html
<!-- Footer-->
<style type="text/css">
    html {
        position: relative;
        min-height: 100%;
    }

    body {
        margin-bottom: 60px;
    }

    .cfooter {
        position: absolute;
        bottom: 0;
        width: 100%;
        height: 60px;
        line-height: 60px;
        background-color: #000000;
    }

    .ccontainer {
        width: auto;
        max-width: 680px;
        padding: 0 15px;
    }
</style>

<footer class="cfooter">
      <div class="ccontainer copy">
        <span class="text-muted">Copyright &copy; TechSwap 2021</span>
      </div>
</footer>

templates/home.html
{% extends 'base.html' %}




{% block content %}
{% include 'homehead.html' %}

   {% include 'home_content.html' %}



{% endblock %}

templates/homehead.html
<header class="bg-dark py-2">
    <div class="container px-4 px-lg-5 my-1">
        <div class="text-center text-white">
            <h1 class="display-4 fw-bolder">Swap in style</h1>
            <p class="lead fw-normal text-white-50 mb-0">Welcome to TechSwap</p>
        </div>
    </div>
</header>

templates/nav.html
{% if user.is_authenticated %}
    {% include "navbar/nav_authenticated.html" %}
{% else %}
    {% include "navbar/navbar.html" %}
{% endif %}

templates/notyours.html
{% extends 'base.html' %}

{% block content %}
    {% include 'notyourshead.html' %}

    <p>
        {{ my_text }}
    </p>

    <script>
    setTimeout(function(){
        window.location.href = "{% url 'swapshop:home' %}"
    }, 2000);
</script>

{% endblock %}

templates/notyourshead.html
<header class="bg-danger py-2">
    <div class="container px-4 px-lg-5 my-1">
        <div class="text-center text-white">
            <h1 class="display-4 fw-bolder">Not Your Item</h1>
            <p class="lead fw-normal text-white-50 mb-0">Welcome to TechSwap....</p>
        </div>
    </div>
</header>

templates/search.html
{% extends 'base.html' %}

{% block title %}Search {% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h3>Search Results for <span class="text-info">"{{request.GET.keyword}}"</span></h3>
            <hr>
            {% for result in results %}
            <div class="row">
                <div class="col-md-3">
                    <img src="{{result.image.url}}" class="img-fluid" alt="">
                </div>
                {% if user.is_authenticated %}
                    <div class="col-md-9">
                        <h4><a href="{% url 'swapshop:itemdetail' result.slug %}">{{result.title}}</a></h4>
                        <h5>City: {{result.city}}</h5>
                        <p>{{result.description|truncatewords:50}}</p>
                    </div>
                {% else %}
                    <div class="col-md-9">
                        <h4><a href="{% url 'swapshop:guestitemdetail' result.slug %}">{{result.title}}</a></h4>
                        <p>{{result.description|truncatewords:50}}</p>
                    </div>
                {% endif %}
            </div>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock %}

templates/social.html
{% extends 'base.html' %}

{% block content %}
{% include 'socialhead.html' %}
    <h1>Community Pages</h1>
    <p>This is a template</p>


{% endblock %}

templates/socialhead.html
<header class="bg-dark py-2">
    <div class="container px-4 px-lg-5 my-1">
        <div class="text-center text-white">
            <h1 class="display-4 fw-bolder">Community</h1>
            <p class="lead fw-normal text-white-50 mb-0">Welcome to the TechSwap Community Pages....</p>
        </div>
    </div>
</header>

templates/userlogin.html
{% extends 'base.html' %}

{% block title %}User Login{% endblock %}

{% block content %}
<style>
    .errorlist {
        color: red;
    }
</style>
<div class="container">
    <div class="row">
        <div class="col-md-6 mx-auto">
            <h3>User Login Form</h3>
            <hr>
            <form action="" method="POST">
                {% csrf_token %}
                {{form.as_p}}
                <button class="btn btn-primary">Login as a User</button>
                {% if error %}
                <li style="color: red;">{{error}}</li>
                {% endif %}
            </form>
            <p>Forgot Password?<a href="{% url 'usermgmt:passworforgot' %}">Reset now.</a></p>
            <p> or dont have account? <a href="{% url 'usermgmt:userregistration' %}{% if request.GET.next %}?next={{request.GET.next}}{% endif %}">Register here</a></p>
        </div>
    </div>
</div>
{% endblock %}