TechSwap/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
import debug_toolbar

urlpatterns = [
    path("ts-admin/", admin.site.urls),
    path("", include("swapshop.urls")),
    path("accounts/", include("allauth.urls")),
]

if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include(debug_toolbar.urls)),
    ]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

swapshop/urls.py
from django.urls import path

# from django.views.generic import TemplateView

from .views import (
    HomeView,
    AboutView,
    AllItemsView,
    ItemDetailView,
    GuestItemDetailView,
    ItemCreateView,
    AddToWishListView,
    MyWishListView,
    MyItemListView,
    ManageWishListView,
    EmptyWishListView,
    UserProfileView,
    UserItemDetailView,
    SearchView,
    RemWishListItemView,
    RemMyItemView,
    ArcMyItemView,
    NotYourItemView,
    MySwapListView,
    RequestSwapView,
    EmptySwapListView,
    RemSwapListItemView,
    SwapDetailView,
    AddToSwapListView,
    WLItemDetailView,
    AlreadyRequestedView,
    SuccessView,
    SwapSuccessView,
)

app_name = "swapshop"
urlpatterns = [
    # Client side pages
    path("", HomeView.as_view(), name="home"),
    path("about/", AboutView, name="about"),
    path("success/", SuccessView, name="success"),
    path("swapsuccess/", SwapSuccessView, name="swapsuccess"),
    path("all-items/", AllItemsView.as_view(), name="allitems"),
    path("item/<slug:slug>/", ItemDetailView.as_view(), name="itemdetail"),
    path("wlitem/<slug:slug>/", WLItemDetailView.as_view(), name="wlitemdetail"),
    path("swap/<slug:slug>/", SwapDetailView.as_view(), name="swapdetail"),
    path(
        "guestitem/<slug:slug>/", GuestItemDetailView.as_view(), name="guestitemdetail"
    ),
    path("additem/", ItemCreateView.as_view(), name="itemcreate"),
    path("add-to-wlist-<int:itm_id>/", AddToWishListView.as_view(), name="addtowlist"),
    path("add-to-slist-<int:itm_id>/", AddToSwapListView.as_view(), name="addtoslist"),
    path("my-item-list/", MyItemListView.as_view(), name="myitemlist"),
    path("my-wish-list/", MyWishListView.as_view(), name="mywishlist"),
    path("my-swap-list/", MySwapListView.as_view(), name="myswaplist"),
    path("manage-list/<int:cp_id>/", ManageWishListView.as_view(), name="managelist"),
    path("emptywishlist/", EmptyWishListView.as_view(), name="emptywishlist"),
    path("rem-wlitem/<slug:slug>/", RemWishListItemView.as_view(), name="remwlitem"),
    path("rem-myitem/<slug:slug>/", RemMyItemView.as_view(), name="remmyitem"),
    path("arc-myitem/<slug:slug>/", ArcMyItemView.as_view(), name="arcmyitem"),
    path("emptyswaplist/", EmptySwapListView.as_view(), name="emptyswaplist"),
    path("rem-slitem/<slug:slug>/", RemSwapListItemView.as_view(), name="remslitem"),
    path("reqswap-<int:itm_id>/", RequestSwapView, name="reqswap"),
    path("notyouritem/", NotYourItemView.as_view(), name="notyouritem"),
    path("alreadyrequested/", AlreadyRequestedView.as_view(), name="alreadyrequested"),
    path("accounts/profile/", UserProfileView.as_view(), name="userprofile"),
    path(
        "accounts/profile/item-<int:pk>/",
        UserItemDetailView.as_view(),
        name="useritemdetail",
    ),
    path("search/", SearchView.as_view(), name="search"),
]

swapshop/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models.fields import TextField
from django.db.models.signals import post_save
from allauth.account.signals import user_signed_up
from django.dispatch import receiver, Signal
from django.urls import reverse
from location_field.models.plain import PlainLocationField
from django.utils.text import slugify
from django.core.mail import EmailMessage


from django.conf import settings
from django.utils.translation import ugettext_lazy as _

import random

# Item Management
class Category(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)

    class Meta:
        ordering = ["title"]

    def __str__(self):
        return f"{self.title}"

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        value = self.slug
        self.slug = slugify(value, allow_unicode=True)
        super().save(*args, **kwargs)


ITEM_CONDITION = (
    (s, s)
    for s in ("Like New", "Excellent", "Good", "Used", "Poor", "Spares or Repair")
)


class Item(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True, default="", editable=True, max_length=255)
    category = models.ForeignKey(Category, on_delete=models.DO_NOTHING)
    description = models.TextField(max_length=500, default=None)
    image = models.FileField(upload_to="items")
    condition = models.CharField(max_length=50, choices=ITEM_CONDITION)
    created_at = models.DateTimeField(auto_now_add=True)
    city = models.CharField(max_length=255)
    location = PlainLocationField(based_fields=["city"], zoom=7)
    swap_comp = models.BooleanField(default=False)
    archived = models.BooleanField(default=False)
    active = models.BooleanField(default=False)
    swap_agrd = models.BooleanField(default=False)
    created_by = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    view_count = models.PositiveIntegerField(default=0)

    def __str__(self):
        return f"{self.title} {self.slug}"

    def get_absolute_url(self):
        kwargs = {"pk": self.id, "slug": self.slug, "my_id": self.id}
        return reverse("itemdetail", kwargs=kwargs)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        value = self.slug
        self.slug = slugify(
            value,
            allow_unicode=True,
        )
        super().save(*args, **kwargs)


class ItemImage(models.Model):
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    image = models.FileField(upload_to="items/multimages/")

    def __str__(self):
        return self.item.title


class WishList(models.Model):
    client = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"WishList: {self.id}"


class WishListItem(models.Model):
    item_list = models.ForeignKey(WishList, on_delete=models.CASCADE)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)

    def __str__(self):
        return f"WishList: {self.item_list.id} WishlistItem: {self.id}"


class SwapList(models.Model):
    client = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"SwapList: {self.id}"


class SwapListItem(models.Model):
    item_list = models.ForeignKey(SwapList, on_delete=models.CASCADE)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)

    def __str__(self):
        return f"SwapList: {self.item_list.id} SwaplistItem: {self.id}"


SWAP_STATUS = (
    (s, s)
    for s in (
        "Item Active",
        "Item Wanted",
        "Swap Initiated",
        "Swap Agreed",
        "Swap Complete",
        "Swap Cancelled",
    )
)


class Swap(models.Model):
    swap_list = models.ForeignKey(SwapList, on_delete=models.CASCADE)
    requested_by = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True, blank=True
    )
    email_from = models.EmailField(null=True, blank=True)
    email_to = models.EmailField(null=True, blank=True)
    swap_status = models.CharField(max_length=50, choices=SWAP_STATUS)
    message_sent = models.TextField(max_length=2000, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    swap_completed = models.BooleanField(default=False, null=True, blank=True)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)

    def __str__(self):
        return f"Swap: {self.id}"


class Location(models.Model):
    name = models.CharField(max_length=200)
    town = models.CharField(max_length=200)
    city = models.CharField(max_length=200)
    county = models.CharField(max_length=200)
    country = models.CharField(max_length=200)
    zip = models.CharField(max_length=200)

    def __str__(self):
        return f"{self.name} {self.town} {self.country}"


class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    phone = models.CharField(max_length=200, null=True, blank=True)
    image = models.FileField(
        upload_to="profile_images",
        null=True,
        blank=True,
        default="profile_images/dummy/dummy-avatar.png",
    )
    rating = models.IntegerField(default=0, blank=True)
    feedback = models.ManyToManyField("Feedback", related_name="Feedback", blank=True)
    items = models.ManyToManyField(Item, related_name="Items", blank=True)
    bio = models.TextField(_("bio"), max_length=500, blank=True)
    birth_date = models.DateField(null=True, blank=True)

    def __str__(self):
        return f"{self.user} {self.rating} {self.feedback}"


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()


welcome_Message = """
A Big Thank You for signing up to TechSwap.UK. We hope you enjoy your time on our site.
Our aim is to provide you, the end users, a way of swapping unused tech items with other 
likeminded TechSwap.UK users. Our hope is that this will become a useful marketplace for 
those users wishing to pass on technology that they no longer use in exchange for items 
other users may have to swap. Our intention is that this is done in a friendly and 
convenient manor for all involved. We just facilitate the exchange, it is down to you as 
an end user to negotiate for items you may want. 
This is not a selling site. we do not expect to see items listed for cash/quick sale etc.
Our site is for use by like minded people who want to "Pay it forward" and swap unused 
technology for something they may need. 

Users found abusing the system will be removed. 

Above all please enjoy using the site, and if at anytime you find something wrong or have
any issues please don't hesitate to contact us using the form on the About page. 

Thank you, 
The Techswap.UK Team

"""


@receiver(user_signed_up, sender=User)
def send_welcome_email(sender, **kwargs):
    email = EmailMessage(
        "Welcome to TechSwap.UK",
        welcome_Message,
        "info@techswap.uk",
        [User.email],
        reply_to=[
            "donotreply@TechSwap.UK",
        ],
    )

    email.send()


class Address(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    house_num = models.CharField(max_length=200, null=True, blank=True)
    street = models.CharField(max_length=200, null=True, blank=True)
    town = models.CharField(max_length=200, null=True, blank=True)
    city = models.CharField(max_length=200, null=True, blank=True)
    county = models.CharField(max_length=200, null=True, blank=True)
    country = models.CharField(max_length=200, null=True, blank=True)
    zipcode = models.CharField(max_length=200, null=True, blank=True)

    def __str__(self):
        return f"{self.street} {self.town} {self.country}"


@receiver(post_save, sender=User)
def create_user_address(sender, instance, created, **kwargs):
    if created:
        Address.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_address(sender, instance, **kwargs):
    instance.address.save()


class Feedback(models.Model):
    item = models.ForeignKey(Item, null=True, on_delete=models.SET_NULL)
    status = models.CharField(max_length=200, null=True, blank=True)
    comments = models.TextField(max_length=300, null=True, blank=True)

    def __str__(self):
        return f"{self.status} {self.comments}"

swapshop/templates/appuserhome.html
{% extends "appuserbase.html" %}

{% block title %}User Home{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h3>Items Available</h3>
            <table class="table">
                <thead>
                    <tr>
                        <th>Item ID</th>
                        <th>Item Name</th>
                        <th>Item Created</th>
                        <th>Location</th>
                        <th>Condition</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in item_list %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td><a href="{% url 'swapshop:itemdetail' item.id %}">{{item.name}}</a></td>
                        <td>{{item.uploaded_at}}</td>
                        <td>{{item.location}}</td>
                        <td>{{item.condition}}</td>

                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

swapshop/templates/dynamicitemdetail.html
{% extends 'base.html' %}

{% block content %}
{% include 'itemhead.html' %}

<div class="container">
    <div class="row">
        <div class="col">
            <div class="m-3 mb-3 shadow-lg p-2 rounded" >
            <h3>Item: {{ item_obj.title }} </h3><hr>
                <div class="card-body p-4">
                    <img src="{{item_obj.image.url}}" class="img-fluid rounded shadow" style="height:250px; object-fit: contain;" alt="{{ item_obj.title }} Image">
                    <div class="row ">
                        {% for ii in item_obj.itemimage_set.all %}
                                <img src="{{ii.image.url}}" class="img-fluid float-left ml-1 rounded mt-2" style="height:100px; width: 150px; object-fit: cover;" alt="{{item_obj.title}} Images">
                        {% endfor %}
                    </div>
                </div>
                <div class="col-md-8">
                    <h5>Categories:
                    {% for cat in item_obj.category.all %}
                        {{ cat.category.title }}  
                    {% endfor %}
                    </h5><hr>
                    <p>Condition: {{ item_obj.condition }}</p>
                    <p>City: {{ item_obj.city }}</p>
                        <div id="map">
                            <img class="img-fluid" src="https://maps.googleapis.com/maps/api/staticmap?center={{ item_obj.location }}&zoom=13&size=600x300&maptype=roadmap&key={{ API_KEY }}">
                        </div>
                    <hr>
                    <p>Description: {{ item_obj.description }}</p>
                    <p>Created by: {{ item_obj.created_by }}
                    {% if not item_obj.created_by.id == user.id %}
                    <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                        <div class="btn-group">
                            <div class="text-center"><a class="btn btn-outline-dark mt-auto m-2" href="{% url 'swapshop:addtoslist' item_obj.id %}" >Add To Swap List</a></div>
                            <div class="text-center"><a class="btn btn-outline-dark mt-auto m-2" href="{% url 'swapshop:addtowlist' item_obj.id %}" >Add To Wish List</a></div>
                            <div class="text-center"><a class="btn btn-outline-dark mt-auto m-2" onclick="goBack()" >Back</a></div>
                        </div>
                    </div>
                    {% else %}
                    <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                        <div class="btn-group">
                            <div class="text-center"><a class="btn btn-outline-dark mt-auto m-2" onclick="goBack()" >Back</a></div>
                        </div>
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>      
{% endblock %}

swapshop/templates/dynamicswaphead.html
<header class="bg-dark py-2">
    <div class="container px-4 px-lg-5 my-1">
        <div class="text-center text-white">
            <h1 class="display-4 fw-bolder">Initiating Swap</h1>
            <p class="lead fw-normal text-white-50 mb-0">Good Luck....</p>
        </div>
    </div>
</header>

swapshop/templates/guestdynamicitemdetail.html
{% extends 'base.html' %}

{% block content %}
{% include 'itemhead.html' %}

<div class="container">
    <h3>{{ item_obj.title }} </h3><hr>
    <div class="row">
        <div class="col">
            <div class=" h-100 shadow-lg p-2 rounded" >
                <div class="card-body p-4">
                    <img src="{{item_obj.image.url}}" style="height:250px; object-fit: contain;" alt="{{ item_obj.name }} Image" class="img-fluid p-3">
                        <div class="row">
                            {% for ii in item_obj.itemimage_set.all %}
                                <div class="col-md-4 p-3">
                                    <img src="{{ii.image.url}}" class="img-fluid float-left ml-1 rounded mt-2" style="height:100px; width: 150px; object-fit: cover;" alt="{{item_obj.name}} Images">
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="col-md-8">
                        <h4>{{ item_obj.title }} </h4>
                        <h5>Categories:
                        {% for cat in item_obj.category.all %}
                            {{ cat.title }}{% comment %} <a href="{{ cat.get_absolute_url }}">{{ cat }}  </a> {% endcomment %}
                        {% endfor %}
                        </h5><hr>
                        <p>Condition: {{ item_obj.condition }}</p>
                        <hr>
                        <p>Description: {{ item_obj.description }}</p>
                    </div>
                    <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                            <div class="btn-group">
                                <div class="text-center"><a class="btn btn-outline-dark mt-auto m-2" href="{% url 'swapshop:home' %}" >Back</a></div>
                            </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

swapshop/templates/itemcreate.html
{% extends 'base.html' %}
{% block title %}Create New Item{% endblock %}
{% block content %}
{% include 'itemhead.html' %}
<div class="container">
    <div class="row">
        <div class="col">
            <div class=" m-3 mb-3 shadow-lg p-2 rounded" >
                <div class="card-body p-4">
                    <h3>Add New Item</h3>
                    <hr>
                    <form method="POST" enctype="multipart/form-data"> 
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button class="btn btn-info">Submit Item</button>
                        {{ form.media }}
                    </form>
                </div>
            </div>
        </div>        
    </div>
</div>

<script async
    src="https://maps.googleapis.com/maps/api/js?key={{ API_KEY }}&libraries=places&callback=activatePlacesSearch">
</script>
{% endblock %}

swapshop/templates/itemdetail.html
{% extends 'base.html' %}

{% block title %}{{item.title}}{% endblock %}

{% block content %}
<div class="container">
    <h3>Product: {{item.title}}</h3><hr>
    <div class="row">
        <div class="col-md-4">
            <img src="{{item.image.url}}" alt="" class="img-fluid">
            <div class="row">
                {% for pi in item.itemimage_set.all %}
                <div class="col-md-4 p-3">
                    <a href="{{pi.image.url}}" target="_blank" rel="noopener noreferrer">
                        <img src="{{pi.image.url}}" class="img-fluid" style="height: 100px; object-fit: contain;" alt="">
                    </a>
                </div>
                {% endfor %}
            </div>
        </div>
        <div class="col-md-8">
            <h4>{{item.title}} (Viewed {{item.view_count}} times)</h4>
            <h5>Category: {{item.category}}</h5>
            <a href="{% url 'swapshop:addtowlist' item.slug %}" class="btn btn-info">Add To WishList</a>
            <hr>
            <hr>
            <p>{{item.description}}</p>
        </div>
    </div>

</div>
{% endblock %}

swapshop/templates/profilehead.html
<header class="bg-dark py-2">
    <div class="container px-4 px-lg-5 my-1">
        <div class="text-center text-white">
            <h1 class="display-4 fw-bolder">My Profile</h1>
            <p class="lead fw-normal text-white-50 mb-0">Welcome to TechSwap....</p>
        </div>
    </div>
</header>

swapshop/templates/success.html
{% extends 'base.html' %}


{% block content %}
{% include 'successhead.html' %}
<div class="container">
    <div class="row">
        <div class="col-md-4">
            <p class="lead">Thank you for your message</p>
        </div>
    </div>
</div>
<script>
    setTimeout(function(){
        window.location.href = "{% url 'swapshop:about' %}"
    }, 3000);
</script>
{% endblock %}

swapshop/templates/swaphead.html
<header class="bg-dark py-2">
    <div class="container px-4 px-lg-5 my-1">
        <div class="text-center text-white">
            <h1 class="display-4 fw-bolder">New Swap</h1>
            <p class="lead fw-normal text-white-50 mb-0">Welcome to TechSwap....</p>
        </div>
    </div>
</header>

swapshop/templates/useritemhead.html
<header class="bg-dark py-2">
    <div class="container px-4 px-lg-5 my-1">
        <div class="text-center text-white">
            <h1 class="display-4 fw-bolder">Wish List Items</h1>
            <p class="lead fw-normal text-white-50 mb-0">Welcome to TechSwap....</p>
        </div>
    </div>
</header>

swapshop/templates/useritemlist.html
{% extends 'base.html' %}



{% block content %}
{% include 'userswaphead.html' %}
<section class="py-5">
<div class="container px-4 px-lg-5 mt-5">
    <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-5 justify-content-center">
    {% for item in items %}
        {% if not item.archived %}
            <div class="col mb-5">
                <div class="card h-100 rounded">
                    <!-- Product image-->
                    <a href="{% url 'swapshop:itemdetail' item.slug %}"><center><img class="card-img-top shadow m-2 mt-3" style="width: 150px; height: 150px" src="{{item.image.url}}" alt="{{item.title}}" /></center></a>
                    <!-- Product details-->
                    <div class="card-body p-4">
                    <div class="text-center">
                        <h5 class="fw-bolder"><a href="{% url 'swapshop:itemdetail' item.slug %}">{{item.title}}</a></h5>
                    </div>
                    </div>
                    <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                        <div class="text-center"><a class="btn btn-outline-dark btn-warning mt-auto" href="{% url 'swapshop:arcmyitem' item.slug %}"  Onclick="return WarningUndoItemArc();">Archive Item</a></div>
                    </div>
                    <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                        <div class="text-center"><a class="btn btn-outline-dark btn-danger mt-auto"  href="{% url 'swapshop:remmyitem' item.slug %}"  Onclick="return WarningUndoItemDel();">Delete Item</a></div>
                    </div>
                    
                </div>
            </div>
        {% else %}
            <div class="col mb-5">
                <div class="card h-100 text-dark bg-light rounded">
                    <!-- Product image-->
                    <a href="{% url 'swapshop:itemdetail' item.slug %}"><center><img class="card-img-top shadow m-2 mt-3" style="width: 150px; height: 150px" src="{{item.image.url}}" alt="{{item.title}}" /></center></a>
                    <!-- Product details-->
                    <div class="card-body p-4">
                    <div class="text-center">
                        <h5 class="fw-bolder"><a href="{% url 'swapshop:itemdetail' item.slug %}">{{item.title}}</a></h5>
                    </div>
                    </div>
                    <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                        <div class="text-center"><a class="btn btn-outline-dark btn-danger mt-auto" href="{% url 'swapshop:remmyitem' item.slug %}" Onclick="return WarningUndoItemDel();" >Delete Item</a></div>
                    </div>
                </div>
            </div>
        {% endif %}
    {% endfor %}
    </div>
</div>
{% endblock %}

swapshop/templates/userprofile.html
{% extends 'base.html' %}



{% block title %}My Profile{% endblock %}

{% block content %}
{% include 'profilehead.html' %}
<div class="container">

    <div class="row mb-3 mt-3 justify-content-md-left">
        <div class="col col-md-left">
            <div class="card h-100 rounded shadow p-3">  
                <h3>Detailed Information</h3><hr>
                    <p><h3>{{user.username}}</h3></p>
                    <img src="{{user.profile.image.url}}" class="card-img-top shadow mb-3" style="width: 80px; height: 80px"  alt="{{user.username}}">
                
                <p><span class="font-weight-bold">Name: </span> {{ user.first_name }} {{ user.last_name }}</p>
                <p><span class="font-weight-bold">Username: </span> {{user.username}}</p>
                <p><span class="font-weight-bold">Email: </span> {{user.email}}</p>
                <p><span class="font-weight-bold">Joined on: </span> {{user.date_joined}}</p>
            </div>
        </div>
        {% if items is not None %}
        <div class="col col-md-auto">
            <div class="card h-100 rounded shadow p-3">
                <h3>Swaps</h3>
                <hr>
                <table class="table">
                    <thead>
                        <tr>
                            <th>Item</th>
                            <th>Swap Status</th>
                            <th>Swap Initiated</th
                        </tr>
                    </thead>
                    <tbody>
                        {% for itm in items %}
                        <tr>
                            <td><a href="{% url 'swapshop:swapdetail' itm.item.slug %}"><center><img class="card-img-top shadow m-2 mt-3" style="width: 80px; height: 80px" src="{{itm.item.image.url}}" alt="{{itm.item.title}}" /></center>{{itm.item.title|truncatechars:15}}</a></td>
                            <td>{{itm.swap_status}}</td>
                            <td>{{itm.created_at|timesince}} ago</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        {% else %}
        <div class="col col-md-auto">
            <div class="card h-100 rounded shadow p-3">
                <h3>No Swaps Made Yet</h3>
            <hr>
            </div>
        </div>
        {% endif %}
        {% if swapreq is not None %}
        <div class="col col-md-auto">
            <div class="card h-100 rounded shadow p-3">
                <h3>Swaps Requested</h3>
                <hr>
                <table class="table">
                    <thead>
                        <tr>
                            <th>Item ID</th>
                            <th>Description</th>
                            <th>Swapped</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for itm in swapreq %}
                        <tr>
                            <td>{{forloop.counter}}</td>
                            <td>{{itm.created_at|timesince}} ago</td>
                            <td>{{itm.swap_agrd|timesince}} ago</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        {% else %}
        <div class="col col-md-auto">
            <div class="card h-100 rounded shadow p-3">
                <h3>No Requests Yet</h3>
            <hr>
            </div>
        </div>
        {% endif %}
    </div>
</div>
{% endblock %}

swapshop/templates/userswaphead.html
<header class="bg-dark py-2">
    <div class="container px-4 px-lg-5 my-1">
        <div class="text-center text-white">
            <h1 class="display-4 fw-bolder">My Items</h1>
            <p class="lead fw-normal text-white-50 mb-0">Welcome to TechSwap....</p>
        </div>
    </div>
</header>

swapshop/templates/userswaplisthead.html
<header class="bg-dark py-2">
    <div class="container px-4 px-lg-5 my-1">
        <div class="text-center text-white">
            <h1 class="display-4 fw-bolder">Swap List Items</h1>
            <p class="lead fw-normal text-white-50 mb-0">Welcome to TechSwap....</p>
        </div>
    </div>
</header>